### ISSUE TITLE
All I get is an endless loading screen - Caddy 0.11.5

### ISSUE THREAD

**Issue by luckman212** [filebrowser/caddy#24] opened 2019-02-12 14:06 UTC
**When did you download File Browser from caddyserver.com?**
2/12/19

**What is your entire Caddyfile?**
```text
http://localhost:8001/upload {

  browse
  log stderr
  gzip

  timeouts 0

  filebrowser / ./ {
    database            filebrowser.db
  }

}
```

**Description**
Just trying to use filebrowser plugin with recent versions of Caddy. It broke with the new overhauled version of Filebrowser I think.

**Expected behaviour**
The Filebrowser UI should display...

**What is happening instead?**
Just get endless "loading dots" - tried refresh, different browser, clearing cache, incognito mode...
![loading](https://user-images.githubusercontent.com/1992842/52640813-5dd17380-2ea5-11e9-9f5d-17b4b0e5f36e.png)

**How to reproduce?**
Install Caddy with filebrowser plugin on macOS 10.14.3. Use Caddyfile above. Start Caddy.

**Comment by luckman212** [comment] 2019-02-12 15:08
Also, when looking at the console log, I am seeing lots of 404 errors, possibly related?

```text
192.168.20.40 - - [12/Feb/2019:09:57:59 -0500] "GET /upload HTTP/1.1" 200 1091
192.168.20.40 - - [12/Feb/2019:09:57:59 -0500] "GET /static/css/chunk-vendors.01e07fc3.css HTTP/1.1" 404 38
192.168.20.40 - - [12/Feb/2019:09:57:59 -0500] "GET /static/css/app.02f31e4b.css HTTP/1.1" 404 38
192.168.20.40 - - [12/Feb/2019:09:57:59 -0500] "GET /static/js/chunk-vendors.eb95ebf6.js HTTP/1.1" 404 38
192.168.20.40 - - [12/Feb/2019:09:57:59 -0500] "GET /static/js/app.cb038b2b.js HTTP/1.1" 404 38
192.168.20.40 - - [12/Feb/2019:09:57:59 -0500] "GET /static/img/icons/apple-touch-icon-152x152.png HTTP/1.1" 404 14
192.168.20.40 - - [12/Feb/2019:09:57:59 -0500] "GET /static/img/icons/favicon-16x16.png HTTP/1.1" 404 14
```

**Comment by wahyd4** [comment] 2019-02-19 00:21
I had the same issue after I updated  `filebrowser`, looks like there is something wrong with the assets' paths.

**Comment by luckman212** [comment] 2019-02-26 23:42
Does _anyone_ have a working Caddyfile that works with filebrowser plugin? Everything I have tried either results in Caddy dying upon start with: `2019/02/26 18:42:10 timeout` or the infinite "loading" screen above + the 404 errors... really frustrating as this all used to "just work" prior to the Filebrowser 2.0 rewrite.

**Comment by hacdias** [comment] 2019-02-27 10:17
@luckman212 it just works here. Did you try cleaning up your browser cache?

**Comment by wahyd4** [comment] 2019-02-27 10:26
@hacdias I can confirm it's not working if file browser doesn't in the root path.

**Comment by hacdias** [comment] 2019-02-27 10:28
@wahyd4 Try opening http://somedomain/abc/. The slash requirement is a known bug.

**Comment by wahyd4** [comment] 2019-02-27 10:34
Just tried and got the same issue. My Caddyfile is
```bash
{$DOMAIN} {
  root /usr/local/www/aria2
  timeouts none
  gzip
  log stdout
  errors stdout
}


{$DOMAIN}/files {
  filebrowser / /data
}
```

**Comment by luckman212** [comment] 2019-03-04 14:08
> @luckman212 it just works here. Did you try cleaning up your browser cache?

@hacdias Yes I did try cleaning browser caches, incognito mode, and even different browser completely (mentioned in first post). I also tried with and without the trailing slash `/` but that didn't work either. Maybe you could post a working config file so I could see if it's something in my config?

**Comment by luckman212** [comment] 2019-03-05 14:28
Installed Caddy 0.11.5 today, still can't get Filebrowser to run. Any tips?

**Comment by wahyd4** [comment] 2019-03-05 23:44
A workaround solution could be 
```bash
http://localhost:8001 {

  browse
  log stderr
  gzip

  timeouts 0

  filebrowser / ./ {
    database            filebrowser.db
  }

}
```

**Comment by hacdias** [comment] 2019-05-11 07:28
Duplicate of #21

**Closed by hacdias** 2019-05-11 07:28 UTC
Labels: bug
